#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    #url: jdbc:mysql://database:3306/platforma?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    url: jdbc:mysql://database:3306/platforma?allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: root